# Generated by Django 2.2 on 2020-12-19 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='seo_title')),
                ('seo_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='seo_description')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='seo_keywords')),
                ('og_title', models.CharField(blank=True, max_length=64, null=True, verbose_name='seo og:title')),
                ('og_image', models.ImageField(blank=True, help_text='изображение, характеризующее страницу', null=True, upload_to='seo', verbose_name='seo og:image')),
                ('og_description', models.TextField(blank=True, help_text='краткое описание страницы длиной не более 300 символов', max_length=300, null=True, verbose_name='seo og:description')),
                ('first_title', models.CharField(max_length=255, verbose_name='Заглавие(1)')),
                ('first_description', models.TextField(verbose_name='Описание главной страницы(1)')),
                ('image', models.FileField(upload_to='')),
                ('second_title', models.CharField(max_length=255, verbose_name='Заглавие(2)')),
                ('second_description', models.TextField(verbose_name='Описание главной страницы(2)')),
                ('play_market', models.URLField(verbose_name='Ссылка на Play Market')),
                ('app_store', models.URLField(verbose_name='Ссылка на App Store')),
                ('facebook', models.URLField(verbose_name='Ссылка на Facebook')),
                ('instagram', models.URLField(verbose_name='Ссылка Instagram')),
                ('telegram', models.URLField(verbose_name='Ссылка на Telegram')),
                ('whatsapp', models.URLField(verbose_name='Ссылка на WhatsApp')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главные страница',
            },
        ),
        migrations.CreateModel(
            name='MainPageFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заглавие возможности')),
                ('image', models.FileField(upload_to='', verbose_name='Иконка возможности')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='landing.MainPage', verbose_name='Главная страница')),
            ],
            options={
                'verbose_name': 'Возможность',
                'verbose_name_plural': 'Возможности',
            },
        ),
        migrations.CreateModel(
            name='MainPageAdvantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заглавие преимущества')),
                ('description', models.TextField(verbose_name='Описание преимущества')),
                ('image', models.FileField(upload_to='', verbose_name='Иконка преимущества')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='landing.MainPage', verbose_name='Главная страница')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
    ]
