# Generated by Django 2.2 on 2020-12-21 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=64, null=True, verbose_name='Заголовок')),
                ('photo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Фотография')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name_plural': 'О компании',
            },
        ),
        migrations.CreateModel(
            name='AdvantagesSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Преимущества')),
            ],
            options={
                'verbose_name': 'Раздел преимуществ',
                'verbose_name_plural': 'Раздел преимуществ',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='Адрес')),
                ('play_market', models.URLField(blank=True, null=True, verbose_name='Ссылка на Play Market')),
                ('app_store', models.URLField(blank=True, null=True, verbose_name='Ссылка на App Store')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Ссылка на Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Ссылка Instagram')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Ссылка на Telegram')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='Ссылка на WhatsApp')),
                ('vk', models.URLField(blank=True, null=True, verbose_name='Ссылка на VK')),
                ('policy', models.URLField(blank=True, null=True, verbose_name='Политика конфиденциальности')),
                ('personal_data', models.URLField(blank=True, null=True, verbose_name='Передача персональных данных')),
                ('index', models.CharField(blank=True, max_length=255, null=True, verbose_name='Копирайт')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=32, null=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Услуги(Раздел)',
                'verbose_name_plural': 'Услуги(Раздел)',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('description', models.BooleanField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратные связи ',
            },
        ),
        migrations.CreateModel(
            name='TextService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=32, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Услуги(Текст)',
            },
        ),
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': 'Главная страница', 'verbose_name_plural': 'Главная страница'},
        ),
        migrations.AlterModelOptions(
            name='mainpageadvantage',
            options={'verbose_name': 'Главная страница(Преимущество)', 'verbose_name_plural': 'Главная страница(Преимущества)'},
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='app_store',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на App Store'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Facebook'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='first_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание(1)'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='first_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок(1)'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка Instagram'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='play_market',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Play Market'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='second_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание(2)'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='second_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок(2)'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Telegram'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на WhatsApp'),
        ),
        migrations.AlterField(
            model_name='mainpageadvantage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mainpageadvantage',
            name='fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='landing.MainPage', verbose_name='Главная страница'),
        ),
        migrations.AlterField(
            model_name='mainpageadvantage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='mainpageadvantage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='mainpagefeature',
            name='fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='landing.MainPage', verbose_name='Главная'),
        ),
        migrations.AlterField(
            model_name='mainpagefeature',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='mainpagefeature',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Фотография')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='landing.Delivery', verbose_name='Доставка')),
                ('texts', models.ManyToManyField(to='landing.TextService', verbose_name='Строки')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Цифра')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='Описание')),
                ('about_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='landing.AboutCompany', verbose_name='О компании')),
            ],
            options={
                'verbose_name_plural': 'По свойства',
            },
        ),
        migrations.CreateModel(
            name='AdvantageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заглавие')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Иконка')),
                ('fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='landing.AdvantagesSection', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
    ]
