# Generated by Django 2.2 on 2020-12-21 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20201221_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='textservice',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_text', to='landing.Delivery', verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='service',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_service_item', to='landing.Delivery', verbose_name='Доставка'),
        ),
    ]
