# Generated by Django 2.2 on 2020-12-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20201221_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='texts',
            field=models.ManyToManyField(blank=True, null=True, to='landing.TextService', verbose_name='Строки'),
        ),
    ]
