# Generated by Django 2.2 on 2020-12-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20201221_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='description',
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_confirmed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Подтвержден'),
        ),
        migrations.AlterField(
            model_name='service',
            name='texts',
            field=models.ManyToManyField(blank=True, null=True, related_name='texts', to='landing.TextService', verbose_name='Строки'),
        ),
    ]
