# Generated by Django 2.2 on 2020-12-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20201222_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcompany',
            options={'verbose_name': 'О компании', 'verbose_name_plural': 'О компании'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_confirmed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Согласен на обработку персональных данных'),
        ),
    ]
