# Generated by Django 2.2 on 2020-12-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20201222_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='heading_kg',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='heading_ru',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='text_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='advantageitem',
            name='description_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='advantageitem',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='advantageitem',
            name='title_kg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заглавие'),
        ),
        migrations.AddField(
            model_name='advantageitem',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заглавие'),
        ),
        migrations.AddField(
            model_name='advantagessection',
            name='title_kg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Преимущества'),
        ),
        migrations.AddField(
            model_name='advantagessection',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Преимущества'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='address_kg',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='address_ru',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='index_kg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Копирайт'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='index_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Копирайт'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='personal_data_kg',
            field=models.URLField(blank=True, null=True, verbose_name='Передача персональных данных'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='personal_data_ru',
            field=models.URLField(blank=True, null=True, verbose_name='Передача персональных данных'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='policy_kg',
            field=models.URLField(blank=True, null=True, verbose_name='Политика конфиденциальности'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='policy_ru',
            field=models.URLField(blank=True, null=True, verbose_name='Политика конфиденциальности'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='title_kg',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='title_ru',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='first_description_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Описание(1)'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='first_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание(1)'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='first_title_kg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок(1)'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='first_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок(1)'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='second_description_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Описание(2)'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='second_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание(2)'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='second_title_kg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок(2)'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='second_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок(2)'),
        ),
        migrations.AddField(
            model_name='mainpageadvantage',
            name='description_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='mainpageadvantage',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='mainpageadvantage',
            name='title_kg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='mainpageadvantage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='property',
            name='description_kg',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='property',
            name='description_ru',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_kg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='textservice',
            name='title_kg',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='textservice',
            name='title_ru',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Название'),
        ),
    ]
